using System;
using System.Device.Gpio;
using System.Diagnostics;
using System.Threading;
using CanSat.E22_900T22D.Wrapper;
using Iot.Device.Button;
using nanoFramework.Hardware.Esp32;


namespace CanSat
{
    public class Program
    {


        //static int loopback_counter = 0;
        static E22 lora = null;
        static ushort broadcastAddress = 0xFFFF;
        const ushort loraAddress = 0x1234;  //55????;
        const byte loraNetworkId = 0x12;    // 850.125 + 18 = 868.125Mhz
      
        public static void Main()
        {
            Debug.WriteLine("Hello from nanoFramework!");

            //Parts of code provided by external author:
            // this code snippet shows usage of the event driven interests generated by Button and Timer
            // assembly:   nanoFramework.Iot.Device.Button
            //
            // more details for study:
            //   https://github.com/nanoframework/nanoframework.IoT.Device/blob/develop/devices/Button/README.md/
            //   https://docs.nanoframework.net/api/System.Threading.Timer.html


            // namespaces ---see upvise

            #region setup
            // ESP32 Hardware, board, chip, etc.
            const int pinButton = 41;
            const int pub_period = 10000;     // miliseconds
            const int pinCOM2_TX = 2;
            const int pinCOM2_RX = 1;

            Blink led = new Blink();//frustrating to discover that this little line is required to init the neo obj

            // Button setup
            GpioButton buttonM5 = new GpioButton(buttonPin: pinButton, debounceTime: TimeSpan.FromMilliseconds(333));

            // Timer setup
            Timer pubTimer = new Timer((s) => FireTelemetryData(), null, 0, pub_period);

          







            Configuration.SetPinFunction(pinCOM2_TX, DeviceFunction.COM2_TX);
            Configuration.SetPinFunction(pinCOM2_RX, DeviceFunction.COM2_RX);
            lora = E22.Create("COM2", loraAddress: loraAddress);
            if (lora != null)
            {
                lora.OnPacketReceived += (sender, e) =>
                {
                    Debug.WriteLine(e.Data.ToString());
                    Blink.Blinks(0, 255, 0, 500, 1, 1);                    //Debug.WriteLine($"nFmem_LoRaRcv={Memory.Run(true)}");
                    /*if (e.Data.ToString().StartsWith("6C6F6F706261636B"))    // loopback
                    {
                        int counter = Interlocked.Increment(ref loopback_counter);
                        lora.SendAsync(e.AddressID, $"Loopback_#{counter:D4}", loraNetworkId);
                    }*/
                    //WriteTextOnScreen($"E22: {e.AddressID:X4} {e.Data}", X: 0, Y: LCD_Y_StatusLine, fcolor: Color.GreenYellow, maxChars: LCD_NumberOfSmallChars, font: SmallFont);
                };
                //sensors.Append("LoRa ");-----prida
            }
            #endregion





            // Button handler/callback
            buttonM5.Press += (sender, e) =>
            {
                // the place to put the code for handling an event from the buttonM5
                FireTelemetryData();
            };



            // Timer handler/callback
            void FireTelemetryData()
            {
                // the place to put the code for handling an event from the pubTimer
                lora.Send(65535, "data");
                Blink.Blinks(0, 0, 255, 100, 1, 1);
            }

            Thread.Sleep(Timeout.Infinite);

            // Browse our samples repository: https://github.com/nanoframework/samples
            // Check our documentation online: https://docs.nanoframework.net/
            // Join our lively Discord community: https://discord.gg/gCyBu8T
        }
    }
}
